#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" Time tools
"""

from __future__ import absolute_import, print_function, unicode_literals

from datetime import datetime, timedelta


TIME_FORMAT = '%Y-%m-%d-%H:%M'

def getDatetime(str, timezone):
	time_obj = datetime.strptime(arg[idx], TIME_FORMAT)
	return time_obj - timedelta(hours=timezone)

def getStrByDatetime(date, timezone):
	time_obj = date + timedelta(hours=timezone)
	return time_obj.strftime(TIME_FORMAT)

def getNow(timezone):
	return datetime.utcnow()
