#!/bin/sh
# Use yapf to format Python code.
# |tool/format| to format all the file diff with origin/master
# |tool/format remote| to format with other remote.
# |tool/format remote --check| to check if the code need format.

if [ "$1" = "" ]; then
	remote='origin'
else
	remote="$1"
fi
remote_branch="${remote}/master"

if [ "$2" = "--check" ]; then
	is_check_mode="yes"
fi

function logMessage {
	if [ "$is_check_mode" == "" ]; then
		echo "$1"
	fi
}

logMessage "Format file diff with ${remote_branch}"

function checkYapf {
	yapf -v > /dev/null
	if [ $? -ne 0 ]; then
		logMessage "Please Install yapf."
		exit 1
	fi
}

if [ "$is_check_mode" != "" ]; then
	yapf_arg=' --diff'
else
	yapf_arg=' -i'
fi

checkYapf
changed_file="$(git diff ${remote_branch} --name-only)"
for file in $changed_file; do
	echo "$file" | grep -Eq ".py$"
	if [ "$?" -ne 0 ]; then
		continue
	fi
	yapf $file $yapf_arg > /dev/null
	yapf_res="$?"
	if [ "$is_check_mode" != "" ] && [ "$yapf_res" -ne 0 ]; then
		exit 1
	fi
done

exit 0
