#!/bin/sh

cd `dirname $0`'/..'

. ./.env

webpack_cmd="./node_modules/.bin/webpack"
server_cmd="python -m mealtime.app"

if [ "$1" == "--dev" ]; then
	DEBUG_MODE=True
	$webpack_cmd --watch &
	$server_cmd &
	wait
else
	DEBUG_MODE=False
	$webpack_cmd
	$server_cmd
fi
